services:
    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
            - 3306:3306
        volumes:
            - db_data:/var/lib/mysql
    email:
        image: mailhog/mailhog
        ports:
            - 1025:1025
            - 8025:8025
    s3:
        image: minio/minio:latest
        ports:
            - 9000:9000
            - 9001:9001
        environment:
            MINIO_ROOT_USER: user
            MINIO_ROOT_PASSWORD: password
        volumes:
            - s3_data:/data
        command: server /data --console-address ":9001"
    redis:
        image: redis:alpine
        ports:
            - 6379:6379
volumes:
    db_data:
        driver: local
    s3_data:
        driver: local
